[meta]
path = "assets/ss_skelly.tga"
format = "RGBA8888"
scale = 1
width = 160
height = 30

[[frames]]
rotated = false
trimmed = false
duration = 100.0
x = 0.0
y = 0.0
w = 32.0
h = 30.0

[[frames]]
rotated = false
trimmed = false
duration = 100.0
x = 32.0
y = 0.0
w = 32.0
h = 30.0

[[frames]]
rotated = false
trimmed = false
duration = 100.0
x = 64.0
y = 0.0
w = 32.0
h = 30.0

[[frames]]
rotated = false
trimmed = false
duration = 100.0
x = 96.0
y = 0.0
w = 32.0
h = 30.0

[[frames]]
rotated = false
trimmed = false
duration = 100.0
x = 128.0
y = 0.0
w = 32.0
h = 30.0
